
if mods["Random_Utilities"] then
	repltech_recipe("ru-behemoth-transport-belt", "device3")
	repltech_recipe("ru-behemoth-underground-belt", "device3")
	repltech_recipe("ru-behemoth-loader", "device3")
	repltech_recipe("ru-behemoth-inserter", "device3")
	repltech_recipe("ru-behemoth-lamp", "device3")
	repltech_recipe("ru-behemoth-solar-panel", "device3")
	repltech_recipe("ru-behemoth-substation", "device3")
	repltech_recipe("ru-behemoth-pipe", "device3")
	repltech_recipe("ru-behemoth-pipe-to-ground", "device3")
	repltech_recipe("ru-behemoth-substation", "device3")
	repltech_recipe("ru-behemoth-accumulator", "device3")
	repltech_recipe("ru-behemoth-splitter", "device3")
	repltech_recipe("bob-construction-robot-5", "device3")
	repltech_recipe("bob-logistic-robot-5", "device3")
	repltech_recipe("speed-module-8", "device3")
	repltech_recipe("micro-assembler-6", "device3")
	repltech_raw("alien-goo", 0.02)
end
